In [ ]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = np.array([(2,5,7),(5,3,9), (9,9,9)])
print(b)

[[2 5 7]
 [5 3 9]
 [9 9 9]]


In [ ]:
c = np.eye((4))
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
b.std()

2.629368792488718